name: CI/CD Status
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm test
        env:
          CI: true
      - name: publish
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ github.ref }}
          echo ${{ github }}
          echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/.npmrc
          npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
